# Generated by Django 3.0.3 on 2020-02-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='add',
            name='check_out',
        ),
        migrations.AddField(
            model_name='add',
            name='check_in_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='add',
            name='check_in_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='add',
            name='check_out_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='add',
            name='check_out_time',
            field=models.TimeField(null=True),
        ),
    ]
