# Generated by Django 3.0.3 on 2020-02-14 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200209_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='add',
            name='check_out_date',
        ),
    ]
