# Generated by Django 3.0.3 on 2020-02-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200214_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
