# Generated by Django 3.0.3 on 2020-02-29 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0004_add_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='old_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('check_in_time', models.TimeField(null=True)),
                ('check_out_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='new_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.add')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
