# Generated by Django 3.0.3 on 2020-02-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_new_booking_old_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
