# Generated by Django 3.0.3 on 2020-03-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_add_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_booking',
            name='user',
        ),
        migrations.AlterField(
            model_name='add',
            name='room_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
