# Generated by Django 3.0.3 on 2020-03-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20200301_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_booking',
            name='new',
        ),
        migrations.AddField(
            model_name='new_booking',
            name='new',
            field=models.ManyToManyField(to='manager.add'),
        ),
    ]
