# Generated by Django 3.0.3 on 2020-03-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20200301_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='old_booking',
        ),
        migrations.RemoveField(
            model_name='new_booking',
            name='new',
        ),
        migrations.AddField(
            model_name='new_booking',
            name='new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.add'),
        ),
    ]
