# Generated by Django 3.0.3 on 2020-03-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_old_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='old_booking',
            old_name='new',
            new_name='old',
        ),
    ]
